// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3KQwFNGblLQVtuMTqHIwD2MkLiI-SlPI',
    appId: '1:308216184117:web:51a96fcedcdc5a803fe07c',
    messagingSenderId: '308216184117',
    projectId: 'ai-english-app-d193d',
    authDomain: 'ai-english-app-d193d.firebaseapp.com',
    storageBucket: 'ai-english-app-d193d.firebasestorage.app',
    measurementId: 'G-31ETGMY6BE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_MdPKnFqHpqSk8K5JmThCES8atHkKLSA',
    appId: '1:308216184117:android:11981a45ffdafa0e3fe07c',
    messagingSenderId: '308216184117',
    projectId: 'ai-english-app-d193d',
    storageBucket: 'ai-english-app-d193d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoN3qpN6W1HrbFC34TncyJ8lMNostofD4',
    appId: '1:308216184117:ios:3b1cc298b7c51ca23fe07c',
    messagingSenderId: '308216184117',
    projectId: 'ai-english-app-d193d',
    storageBucket: 'ai-english-app-d193d.firebasestorage.app',
    iosBundleId: 'com.example.aiEnglishApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAoN3qpN6W1HrbFC34TncyJ8lMNostofD4',
    appId: '1:308216184117:ios:3b1cc298b7c51ca23fe07c',
    messagingSenderId: '308216184117',
    projectId: 'ai-english-app-d193d',
    storageBucket: 'ai-english-app-d193d.firebasestorage.app',
    iosBundleId: 'com.example.aiEnglishApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3KQwFNGblLQVtuMTqHIwD2MkLiI-SlPI',
    appId: '1:308216184117:web:c2b0414492ed02f23fe07c',
    messagingSenderId: '308216184117',
    projectId: 'ai-english-app-d193d',
    authDomain: 'ai-english-app-d193d.firebaseapp.com',
    storageBucket: 'ai-english-app-d193d.firebasestorage.app',
    measurementId: 'G-J1V8XSSFDL',
  );
}
